### ISSUE TITLE
Afterglow version using atmega328p DIP version

### ISSUE THREAD

**Issue by bzhmaddog** [bitfieldlabs/afterglow#10]
Not a bug but I was thinking of using an atmega328p dip chip (the one on the original arduino uno) instead of a nano daughter board.
It is basically the same chip as the one on the nano except for A6 and A7 io missing but thoses are not used on afterglow design af far as I can tell.
The chip would fit in the area where nano goes and just requires a crystal and two caps plus a 2x3 pin header for ICSP programming.

**Comment by bitfieldlabs** [comment]
Yes, that is for sure feasible. You will lose the USB interface to the configuration software, but that may not be an issue to many. If the part crisis would allow it, you could also use the small SMD chip.

**Comment by bzhmaddog** [comment]
I forked your repository and started working on it (v1.3 for now). I am not a big fan of SMD since it requires extra effort for soldering. As for the usb I will provide an ICSP header which is sure less conveniant than usb but I think people who are ready to flash a sketch file through arduino ide will probably also have some arduino lying around to use as programmer
