### ISSUE TITLE
Wrong label for pin1 of J138 

### ISSUE THREAD

**Issue by bzhmaddog** [bitfieldlabs/afterglow#14]
The 'documentation' states
Board revision 1.3 has the J138 OUT connector pin 1 labelled on the wrong side! The pin labelled "1" is actually pin 9.

But what is the action required to mitigate the issue ? just swap the connector orrientation  ? or swap the wires on the harness ?

**Comment by bitfieldlabs** [comment]
No action needed really. The original J138 connectors can be used. It's just that pin 1 is on the other side of the connector, where it should be. The label is just confusing as it suggests that the connector must be the wrong way round.

**Comment by bzhmaddog** [comment]
I see so it is only the label that is wrong but not the traces on the board.

Additionnaly I am wondering why tapping in the 18V to generate the 5V? It is only used to power the Arduino and the few ICs right ? So the LM7805 must be quite hot dropping from 18V to 5V.
Why not using a 12V input ? not enough Amps ? Sorry if it is a dumb question I am not an electronical engineer.

**Comment by bzhmaddog** [comment]
I am starting to wonder if that board is compatible with System 11a. The key pins on J6/J7 on my PDB does not match.

https://imgur.com/a/R12S2Hx

**Comment by bitfieldlabs** [comment]
The LM7805 doesn't get hot as the 5V side is using only very little power. The 18V are needed to drive the lamp matrix, so it makes sense to use it for the 5V regulator as well.

**Comment by bitfieldlabs** [comment]
The board should be fine in Sys11a games, I have personally only tested with Sys11b.
The keys are in a different place than on WPC, you just need to make sure you connect col 1 on the output of the driver board to col 1 on the AG input etc.
https://github.com/bitfieldlabs/afterglow/wiki/Instructions#system-11-installation

**Comment by bzhmaddog** [comment]
I see.
My bad I didn't read the schematic correctly. Obviously the 18V is needed since the board hook into the original lines
So I guess I have to make and adapter to make the rows and cols match.

Thx
