### ISSUE TITLE
Errors on 1.4 PCB

### ISSUE THREAD

**Issue by JustinRudebaugh** [bitfieldlabs/afterglow#9]
First off - Excellent project! I've been reading through everything I can here and on pinball forums.  I've ordered a batch of these to assemble and found a couple issues, and a question after exporting the BOM via KiCAD (for use with Partsbox). 

-R67 is listed as "18v COL".  I see note in wiki about the 18V columns, but would this be a jumper or resistor in the R67 position? If it's a resistor, what's the value?
-J1 is listed in BOM as J137_IN_C, but silkscreen is J138_IN_C
-J2 is listed in BOM as J133_IN_R, but silkscreen is J135_IN_R
-D1, D10, D11, D12, D13, D14, D15, D16, and D17 is not on the silkscreen

Thank you!

**Comment by bitfieldlabs** [comment]
Thanks for the feedback. I will need to make adjustments to the BOM later.

R67 is a zero Ohm resistor. It can be populated as a wire bridge. It is only needed when feeding the +18V from the columns and can be left unpopulated when supplying +18V via J3.

J137 and J138 are connected to the same lines. The same is true for the J133, J134 and J135 connectors. The labels are used a bit inconsistently in the schematic and silkscreen. On the silkscreen I wanted to make clear where to connect to easiest.

Somehow my Kicad footprint for the Schottky diodes doesn't have a proper silkscreen layer. I need to fix that.

Be also aware that I've had several reports of damaged v1.4 boards when people forgot to connect the ground line. It's a design flaw of this +18V from columns design. Personally I prefer the v1.3 board as I also don't mind connecting both +18V and GND to the PPD.

**Comment by bitfieldlabs** [comment]
Fixed silkscreening issues with [5ce20851](https://github.com/bitfieldlabs/afterglow/commit/5ce20851aaa8b1ce0ea9a661658f488daa178507).
R67 documented in BOM.
